# Generated by Django 5.2 on 2025-04-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='saldo',
            field=models.FloatField(default=1000.0),
        ),
        migrations.DeleteModel(
            name='Transacao',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
